
project_id = "dkyeopbzysvdxrldgmjl"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-register]
verify_jwt = false

[functions.stripe-create-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
