// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkyeopbzysvdxrldgmjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreWVvcGJ6eXN2ZHhybGRnbWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5OTUwMDEsImV4cCI6MjA1NDU3MTAwMX0.fjF2Mshzmhr3aoWDdJbOBncAINpqI3rX6PB4lchFrBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);